Fix the Pulse schedule construction benchmarks
Qiskit/qiskit-metapackage pull request #1147
Opened 2021-01-21 16:17 UTC by mtreinish

### Summary

The Pulse schedule construction benchmarks were using the previously
deprecated and now removed SamplePulse class as the pulse to add to a
schedule. This has been failing in benchmark runs since that class was
removed. This commit fixes the failure by using the replacement class
Waveform. This will break compatibility with old versions of terra from
before waveform existed, however since we're unlikely to run a backfill
job for historical data this is an ok tradeoff.

### Details and comments

2021-01-21 16:23 UTC, lcapelluto submitted a review, later dismissed

2021-01-21 16:33 UTC, SooluThomas submitted a review, later dismissed
Thank you!

2021-01-21 18:20 UTC, taalexander requested changes

2021-01-21 18:20 UTC, taalexander commented on test/benchmarks/pulse/schedule_construction.py
>                                DriveChannel(channel)))
```suggestion
                              DriveChannel(channel)),
                              inplace=True)
```
Would also need to be added for other `insert`/`append` instructions. The current benchmarks are broken as the schedule is not actually growing since the returned `sched` is not used.

2021-01-21 22:45 UTC, taalexander commented on test/benchmarks/pulse/schedule_construction.py
> +                              inplace=True)
This change needs to be done for all `append`/`insert` uses on the schedule.

2021-01-29 20:16 UTC, mtreinish commented
I reverted back to the earlier version that just fixed the hard traceback. This is a bit more important than I first realized because this is causing a hard failure on import blocking benhcmarks from running and we haven't had results in ~20days because of this. So I'm going to merge this as is to unblock things. @taalexander feel free to push a follow up PR to address the larger issues you identified with the benchmarks, otherwise I'll try to circle back to it later.

2021-01-29 20:38 UTC, kdk approved these changes

2021-01-29 20:49 UTC, merged