Fixed Spelling Issue #1048
Qiskit/qiskit-metapackage pull request #1193
Opened 2021-03-22 06:11 UTC by bopardikarsoham

I have done the necessary changes to fix the issue.

2021-03-22 06:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=1193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=1193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=1193) it.</sub>

2021-03-27 01:35 UTC, 3yakuya requested changes

2021-03-27 01:35 UTC, 3yakuya commented on docs/getting_started.rst
> +provides `several backends <https://qiskit.org/documentation/locale/ja/apidoc/providers/aer/aer_backends.html>`__
This links specifically to Japanese localized version. Is this intended?

2021-03-27 01:35 UTC, 3yakuya commented on Spelling issue (#1048)
> +<!DOCTYPE html>
What is this entire file providing? I am asking because it's a bit confusing that a spelling issue brings an entirely new file to the repo. LMK if I misunderstand plz!

2021-03-28 17:15 UTC, bopardikarsoham commented on Spelling issue (#1048)
> +<!DOCTYPE html>
Yeah, actually this is related to another pull request "Fixed Broken Links in Doc (Issue #1194) #1196" which has not been merged yet. That's why you might see this change also. My aim is just to show the spelling issue @3yakuya

2021-03-28 17:18 UTC, bopardikarsoham commented on docs/getting_started.rst
> +provides `several backends <https://qiskit.org/documentation/locale/ja/apidoc/providers/aer/aer_backends.html>`__
Yes, when you enter the link you will get an option to change to English. This link is correct for sure. You can review this link issue in another pull request "Fixed Broken Links in Doc (Issue #1194) #1196" @3yakuya

2021-03-29 06:59 UTC, divshacker commented
Hey @bopardikarsoham I have already Fixed this issue. You can check that in #1195.

2021-03-29 07:06 UTC, divshacker commented on docs/getting_started.rst
> +provides `several backends <https://qiskit.org/documentation/locale/ja/apidoc/providers/aer/aer_backends.html>`__
You are doing a mistake @bopardikarsoham . You don't have to put whole link (including https) in this .rst file. But you just have to correct the path of the file rest all will be done by further code.  I have done that same thing. Please try to understand that. 
Thank you

2021-03-29 08:21 UTC, bopardikarsoham commented on docs/getting_started.rst
> +provides `several backends <https://qiskit.org/documentation/locale/ja/apidoc/providers/aer/aer_backends.html>`__
Ok, @divshacker I did what I thought was right nothing else. Yours is certainly a better solution but mine is not completely wrong because the link is taking you to the right place

2021-03-29 08:24 UTC, bopardikarsoham commented
Ok, @divshacker. Although I had put the PR first.

2021-03-29 08:25 UTC, bopardikarsoham commented
And moreover in this PR I just want to show my spelling issue not the link.

2021-03-29 08:35 UTC, divshacker commented on docs/getting_started.rst
> +provides `several backends <https://qiskit.org/documentation/locale/ja/apidoc/providers/aer/aer_backends.html>`__
I know your link is correct and taking it to right place. but that is not required in this .rst file. If you put whole link in that rst file then it will run that link github but it will cause problem in whole code. as the link that is required is only path of the file not the whole link.

2021-03-29 10:12 UTC, bopardikarsoham commented on docs/getting_started.rst
> +provides `several backends <https://qiskit.org/documentation/locale/ja/apidoc/providers/aer/aer_backends.html>`__
Ok @divshacker I know yours is better.

2022-05-25 09:24 UTC, HuangJunye commented
@bopardikarsoham What's the spelling issue here? I don't understand the PR.

2022-05-25 12:18 UTC, jakelishman commented
I think this PR can be closed.  If there are spelling errors in the getting started guide, we welcome corrections, but I think this PR has gone a little wrong - the only correction in the guide changes a valid link to one that's specifically localised to Japanese, which isn't right for the main page, and there's an extra file included.

Thanks for the interest in contributing.  If you're interested in finding more, please have a look at the "good first issue" label on the Qiskit Terra repository.

2022-05-25 12:18 UTC, closed without merging

2022-05-25 12:38 UTC, bopardikarsoham commented
Yes my PR was not in the right direction, this PR can be closed