Update qc_intro.rst
Qiskit/qiskit-metapackage pull request #1208
Opened 2021-04-02 12:15 UTC by jaygambetta

### Summary

### Details and comments

2021-04-02 21:45 UTC, nonhermitian submitted a review, later dismissed

2021-04-05 16:55 UTC, paniash commented on docs/qc_intro.rst
> +information about a qubit's state, often loosing the phase, to be able to represent it as
Minor typo: "loosing" to be changed to "losing".

2021-04-05 16:56 UTC, paniash requested changes

2021-04-05 16:56 UTC, paniash commented on docs/qc_intro.rst
> +information about a qubit's state, often loosing the phase, to be able to represent it as
Minor typo: "loosing" to be changed to "losing".

2021-04-07 01:41 UTC, nonhermitian approved these changes

2021-04-07 11:02 UTC, merged