Update intro_tutorial1.rst
Qiskit/qiskit-metapackage pull request #1209
Opened 2021-04-02 12:56 UTC by jaygambetta

### Summary

### Details and comments

2021-04-05 16:53 UTC, paniash requested changes

2021-04-05 16:53 UTC, paniash commented on docs/intro_tutorial1.rst
> +    # supported by the backend (not needed for simiple circuits)
A minor typo: to be changed to "simple".

2021-04-05 16:53 UTC, paniash commented on docs/intro_tutorial1.rst
> +    # supported by the backend (not needed for simiple circuits)
To maintain consistency, variable name to be changed to `compiled_circuit` instead of `complied_circuit`.

2021-04-07 01:42 UTC, nonhermitian approved these changes

2021-04-07 13:12 UTC, merged