Separate stable version list from language menu
Qiskit/qiskit-metapackage pull request #1579
Opened 2022-07-28 17:20 UTC by mtreinish

### Summary

The language menu is using a widget/theme element rst-versions which in
the original rtd theme (which is the grandparent of the qiskit sphinx
theme) is a pop up/dropdown menu that has a bunch of extra information
in it that can be used to list different versions of the documentation
as well as download links. In #1261 that functionality was used to add a
list of stable versions to the sidebar since it was the logical place
for it. However, this has apparently been a source of confusion for most
users as unless they have prior knowledge about the previous version
links being on the same menu as the language selection and the
availability of old versions of the documentation goes unnoticed. This
commit addresses this by splitting the previous versions list out of the
language selector drop down and just adding a list to the bottom of the
side bar. We can change the formatting and style of this as needed in
the future, but at least for right now it gives us a clear location for
links to old version of the documenation.

### Details and comments
Fixes #1266

2022-07-28 17:35 UTC, mtreinish commented
This is what the side bar looks like when I build this locally:

![Screenshot_2022-07-28_13-34-09](https://user-images.githubusercontent.com/2447371/181601635-4ab4c961-edc2-4c0c-af69-b7e555d72a65.png)

and with the language menu selected

![Screenshot_2022-07-28_13-34-33](https://user-images.githubusercontent.com/2447371/181601643-e085f15a-db2e-445f-adcb-cd14e6f89213.png)

2022-07-28 21:18 UTC, 1ucian0 commented on docs/_templates/stable_versions.html
> +      {% for version in version_list %}
I think it would make sense to have newer first:
```suggestion
      {% for version in version_list | sort(reverse=True) %}
```

Probably, the right way of thing this is in `_get_version_list` with `StrictVersion` because semantic versioning:
```
from distutils.version import StrictVersion
...
    version_list.sort(key=StrictVersion)
    return version_list
```

2022-07-28 21:21 UTC, 1ucian0 requested changes
just a small comment. Thanks for taking care of this!

2022-07-28 22:15 UTC, mtreinish commented on docs/_templates/stable_versions.html
> +      {% for version in version_list %}
I think we should be ok because even with semver I can't think of a case where this will sort incorrectly just using a string sort of the version number. The only version tag I could see having a potential issue is if we did prereleases where `0.2.0` would be less than `0.2.0rc0`. But for the metapackage we don't do pre-releases this won't come up.

But I think pushing a follow up to use [packaging](https://packaging.pypa.io/en/latest/index.html)  (which replaced the deprecated `distutils.version` module) is a good idea.

2022-07-29 10:38 UTC, 1ucian0 approved these changes

2022-07-29 10:39 UTC, merged