Bugfix: docs header svg is now clickable
Qiskit/qiskit-metapackage pull request #1608
Opened 2022-09-27 19:17 UTC by javabster

### Summary
The svg for the header image on qiskit.org/documentation has hyperlinks for each title, but they are currently only clickable if a user opens the image separately. This PR updates the `index.rst` file to make the svg links clickable from the webpage (this file now uses the same html object used in `docs/contrubute_to_qiskit` to make the flowchart links clickable)

2022-09-27 19:26 UTC, jakelishman submitted a review, later dismissed
Yeah, I'm pretty sure this is the fix you need. This is what triggers the direct embedding of the SVG, rather than linking it through an `img` tag - I forgot the last time around.

2022-09-27 19:27 UTC, javabster commented
@jakelishman same i forgot too!

I'm just fixing up the formatting so it's aligned in the centre again then should be good to go

2022-10-04 10:03 UTC, HuangJunye requested changes
Thanks for the fix! I can verified in the artifacts that the image is now clickable. 

However, the image overflow and it covers the TOC on the right. And simply scaling to 850px (max width of the main text) still causes problems if you rescale the window size. 

![qiskit architecture svg pr](https://user-images.githubusercontent.com/7631333/193792126-814981e2-216a-4661-b8b7-bab16e81b53f.gif)

Can you try this instead (from [this answer](https://stackoverflow.com/questions/34777943/insert-clickable-svg-image-into-sphinx-documentation))? 

```rst
.. raw:: html

  <div class="figure align-center">
     <object data="myfile.svg" type="image/svg+xml"></object>
  </div>

```

2022-10-04 10:04 UTC, HuangJunye commented
Another comment is that the link for IBM provider is qiskit-ibm-runtime not qiskit-ibm-provider. Is that intended?

2022-10-04 10:11 UTC, jakelishman commented
Inserting as an "object" doesn't _feel_ right to me, but my intuition about HTML/CSS is pretty trash.  The SVG file having a hardcoded absolute width in its tag is what causing the resizing issues.  That should probably be blank (defaults to 100% of the container it's in) - I think if there's scaling issues with what constitutes the viewport, there's a `viewBox` attribute or something?

2022-10-04 15:27 UTC, javabster commented
thanks for the comments guys! Now I'm back from holiday I'll play around with the CSS and try get it sorted. Any suggestions always appreciated!

2022-10-04 18:42 UTC, javabster commented
@jakelishman @HuangJunye CSS fixed! ✨ ✨ ✨ 

<img width="1575" alt="Screenshot 2022-10-04 at 2 38 16 PM" src="https://user-images.githubusercontent.com/23662430/193899991-a4c6a06f-37ce-4d2d-9c34-3052eb8ee845.png">
<img width="400" alt="Screenshot 2022-10-04 at 2 38 27 PM" src="https://user-images.githubusercontent.com/23662430/193899997-97c4170d-d813-479c-96b7-4c2517b5beae.png">

2022-10-04 19:43 UTC, jakelishman approved these changes
Looks great!  Once #1610 merges to fix the CI issue you've got here, I think we're good, unless Junye spots anything else?

2022-10-05 08:28 UTC, HuangJunye reviewed
It works perfectly now! I think it would be good if we don't need to use three lines of ` .. raw:: html`. I also notice the image has change. Did you need to scale down the size of the image in order to fit with the main text container?

2022-10-05 08:28 UTC, HuangJunye commented on docs/index.rst
> +.. raw:: html
Just nitpicking. Three lines of `raw:: html` looks ugly. According to [this article](https://vecta.io/blog/best-way-to-embed-svg), `<object>` is recommended if interactivity is required.
<img width="708" alt="image" src="https://user-images.githubusercontent.com/7631333/194014997-5ae41992-52de-498d-bef0-423fc300f0cd.png">

I haven't built the doc myself. Did what I suggest yesterday work?

```rst
.. raw:: html
<div class="figure align-center">
   <object data="images/qiskit_main.svg" type="image/svg+xml"></object>
</div>
```

2022-10-05 21:06 UTC, javabster commented on docs/index.rst
> +.. raw:: html
thanks Junye, yep I tried this but couldn't get the image to render 😢 I tried both object and img and whatever other suggestions google recommended in the time i had but the double raw html was the only solution that actually worked

2022-10-05 21:09 UTC, javabster commented on docs/index.rst
> +.. raw:: html
and to answer your q about the image change it looks different because I had to remove the `width` and `height` props on the svg file itself, in order to get the html to override the sizing, which is why it looks different in github.  If you click the 'display source diff' button on the top right of the file diff view you can see the actual code i changed 😄 

<img width="1436" alt="Screenshot 2022-10-05 at 5 08 46 PM" src="https://user-images.githubusercontent.com/23662430/194164126-e57a87c4-3b45-4aca-98a6-8c34bd2a2e6e.png">

2022-10-07 08:19 UTC, HuangJunye approved these changes

2022-10-07 08:19 UTC, HuangJunye commented on docs/index.rst
> +.. raw:: html
LGTM. Thanks for the explanations!

2022-10-07 09:27 UTC, merged