publish Ignis docs
Qiskit/qiskit-metapackage pull request #165
Opened 2019-03-04 17:01 UTC by derivation

now that Ignis is on PyPi

2019-03-04 17:18 UTC, derivation commented
updating global install instructions to include Ignis

2019-03-04 20:39 UTC, lzdanski submitted a review, later dismissed
Hey @derivation - I made a couple of comments and suggestions. It looks great and the only things I found were minor (typo, accessibility).

2019-03-04 20:39 UTC, lzdanski commented on docs/install.rst
> +ourself inside this environment run:
```suggestion
yourself inside this environment run:
```

2019-03-04 20:39 UTC, lzdanski commented on docs/install.rst
> +* `Qiskit Aer <https://github.com/Qiskit/qiskit-aer/blob/master/.github/
Is there any significance in where the line breaks occur? It's the only thing standing out to me that the number of characters in each line seem different.

2019-03-04 20:39 UTC, lzdanski commented on docs/install.rst
> +Navigate to the Advanced tab and click the Generate button in the API Token
We should have a conversation about styling UI elements to be distinct in addition to capitalizing them. It helps users know what is a command vs an element to interact with. So something like: 

Navigate to the **Advanced** tab and click the **Generate** button in the *API Token*. 

It'd have to address the whole doc set, so I don't think it's a barrier to merging this PR.

2019-03-04 20:39 UTC, lzdanski commented on docs/install.rst
>    IBM Q Network members must specify more than just an API token, as explained below.
```suggestion
  If you are an IBM Q Network members, you must specify more than just an API token by using the following commands.
```

2019-03-04 20:39 UTC, lzdanski commented on docs/install.rst
>    IBM Q Network members must specify more than just an API token, as explained below.
This is just an accessibility vocab change. "Above/Below" use the UI design to indicate order of presentation, but if you're using a screen reader you perceive it as "before/after" because they read from beginning/top to end/bottom.

2019-03-04 21:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=165) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=165) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: derivation<br/>:x: lzdanski<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=165) it.</sub>

2019-03-04 21:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=165) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=165) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: derivation<br/>:x: lzdanski<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=165) it.</sub>

2019-03-04 21:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=165) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=165) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: derivation<br/>:x: lzdanski<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=165) it.</sub>

2019-03-04 21:34 UTC, derivation commented on docs/install.rst
> +* `Qiskit Aer <https://github.com/Qiskit/qiskit-aer/blob/master/.github/
Yes, there's a character line limit that gets checked when the docs are built. The max is currently set to 100 in the build.

2019-03-04 21:35 UTC, derivation commented on docs/install.rst
> +Navigate to the Advanced tab and click the Generate button in the API Token
Oh, good idea. I'll make these bold for now.

2019-03-05 13:24 UTC, mtreinish requested changes
LGTM, just one small thing to fix on the install doc. I think this and https://github.com/Qiskit/qiskit/pull/168 are all we need before we can push the release with ignis.

2019-03-05 13:24 UTC, mtreinish commented on docs/install.rst
> +  pip install qiskit qiskit-aqua qiskit-ignis
This shouldn't be needed. Since https://github.com/Qiskit/qiskit/pull/164 added ignis to the requirements for the meta repository it will install ignis for us.

2019-03-05 13:24 UTC, mtreinish commented on docs/install.rst
> +  pip install qiskit[visualization] qiskit-aqua qiskit-ignis
Same here

2019-03-05 13:57 UTC, mtreinish approved these changes

2019-03-05 15:08 UTC, merged