Added benchmarks for isometries
Qiskit/qiskit-metapackage pull request #315
Opened 2019-06-08 11:09 UTC by rabaniten

Added benchmarks for the run-time and the gate counts for the decomposition of isometries from 
m to n qubits for different values of m and n.

2019-06-10 15:55 UTC, mtreinish requested changes
Thanks for writing this, it LGTM for the most part. Besides the lint failure, we should also detect whether the `iso` method is present or not on the quantum circuit object. That way this benchmark will only be attempted to run on commits after the dependent PR in terra lands (the benchmarks are run on current master as well as at any point in the git log for comparison purposes). I think this wi'll be ready to go after that.

2019-06-10 15:55 UTC, mtreinish commented on test/benchmarks/isometry.py
> +        qc.iso(iso, q[:m], q[m:])
This depends on Qiskit/qiskit-terra#2600 having merged right? Can we add:

```
if not hasattr(qc, 'iso'):
    raise NotImplementedError
```

before this line? That way when someone tries to run the benchmarks on an earlier commit this will just be skipped.

2019-06-13 12:32 UTC, rabaniten commented on test/benchmarks/isometry.py
> +        qc.iso(iso, q[:m], q[m:])
Thanks a lot for the prompt feedback! I have updated it as you suggeted (and fixed some other minor things)

2019-06-28 19:23 UTC, mtreinish requested changes
I think these benchmarks are good, and I was ready to approve it. But, we need to change the return format for `track_gate_counts()`. This won't work while returning a dictionary.

2019-06-28 19:23 UTC, mtreinish commented on test/benchmarks/isometry.py
> +        return circuit.count_ops()
The docs say the return for a generic tracking benchmark are numeric (https://asv.readthedocs.io/en/stable/writing_benchmarks.html#tracking-generic), but I wasn't sure if a dict of numeric values would count. I just ran this locally to check and it does not work. While the benchmarks run fine, when it comes to aggregating the results for publishing, it fails when it tries to do numeric analysis (well if an average counts as analysis :p) on the results. So we either need to change the result to be a single number, or change the metric we're tracking to be a single number per execution.

2019-07-01 17:22 UTC, rabaniten commented on test/benchmarks/isometry.py
> +        return circuit.count_ops()
Thanks for noting this. I have updated the following:
-We consider the number of C-NOT gates as a cost measure (the number of single-qubit gates is anyway bounded by about 4 times the number of C-NOTs, and the C-NOTs are usually much more expensive to implement)
-I have updated the parameter range to avoid evaluating non valid isometries (we must have n>=m for an isometry from m to n qubits)

2019-07-02 19:32 UTC, mtreinish requested changes
Thanks for the quick update. There's just one small quick inline code simplification I think we should make here. After that small change is made this LGTM and I'll merge.

2019-07-02 19:32 UTC, mtreinish commented on test/benchmarks/isometry.py
> +            cnot_count = counts['cx']
We can replace L45-L48 with `counts.get('cx', 0)` which will use 0 as a default if cx is not defined in the dictionary.

2019-07-02 20:08 UTC, mtreinish approved these changes
I took care of the simplification I mentioned before, and also set a seed for all functions that took one to reduce noise in the benchmarks. Also moved the skip raise as early as I could in the `setup()` (which are all things I noticed on a second look). With this it's ready to merge now.

2019-07-02 21:01 UTC, merged