update qft benchmark: add Aer timing, go up to 24 qubits
Qiskit/qiskit-metapackage pull request #361
Opened 2019-07-05 01:58 UTC by ajavadia

updates to QFT benchmark

2019-07-08 13:48 UTC, mtreinish requested changes
LGTM, but besides the lint failure there are a couple inline comments. Mostly we need to version the benchmark now to mark it as different from previous results. Also, if we're going to execute circuits in aer we'll need to make sure it's installed. But, it raises bigger questions about what we're benchmarking there, if we're trying to measure aer performance over time this probably isn't the right place to do it.

2019-07-08 13:48 UTC, mtreinish commented on test/benchmarks/qft.py
> +from qiskit import Aer
If we're going to execute the circuit on aer now too we'll have to install it in the benchmark env. Can you add a commit like: https://github.com/Qiskit/qiskit/pull/306/commits/b03f6744d47d22b2f601e2cc2eb019dd335b2aa2 to make sure we install aer in the asv environment. That being said these benchmarks track terra's performance over time, we'll always be testing the circuit on a fixed version of aer because of that, is there still value in benchmarking the execution?

2019-07-08 13:48 UTC, mtreinish commented on test/benchmarks/qft.py
>  class QftTranspileBench:
We should add a version parameter here to make it explicit that the results here are different from previous executions of the qft benchmarks. Just add a parameter to the class:

`version = 2`

2019-08-13 12:00 UTC, jaygambetta commented
@ajavadia and @mtreinish did you close on this.

2019-08-14 19:23 UTC, mtreinish commented
@jaygambetta there hasn't been any update to this since my comments last month. I assume it's lower priority and @ajavadia hasn't had a chance to look at it more

2020-01-07 21:55 UTC, mtreinish commented
I'm going to close this since there hasn't been any recent activity. Feel free to reopen it if you'd like to pick this up again.

2020-01-07 21:55 UTC, closed without merging