[WIP] Improve "Overview" and "Index" pages of documentation
Qiskit/qiskit-metapackage pull request #380
Opened 2019-07-19 17:45 UTC by SooluThomas

### Summary
Moved content from overview.rst to index.rst.

2019-07-19 19:01 UTC, derivation requested changes

2019-07-19 19:01 UTC, derivation commented on docs/index.rst
> +
```suggestion
Qiskit Artificial Intelligence (AI) allows users with different levels of
experience to execute AI experiments and contribute to the quantum computing AI
software stack. Users with a pure AI background or interests can continue to
configure AI problems without having to learn the details of quantum computing.
```

2019-07-19 19:01 UTC, derivation commented on docs/index.rst
> +
```suggestion
Qiskit Optimization allows users with different levels of experience to execute
optimization experiments and contribute to the quantum computing optimization
software stack. Users with a pure optimization background or interests can
continue to configure optimization problems without having to learn the details
of quantum computing.
```

2019-07-19 19:01 UTC, derivation commented on docs/index.rst
> +
```suggestion
Qiskit Finance allows users with different levels of experience to execute
financial analysis and optimization experiments and contribute to the quantum
computing finance software stack. Users with a pure finance background or
interests can continue to configure financial analysis and optimization problems
without having to learn the details of the underlying quantum computing system.
```

2019-07-23 03:15 UTC, pistoia commented on docs/index.rst
> +   for quantum computing. Aqua is accessible to domain experts in chemistry, optimization
chemistry, optimization, **finance** and AI

2019-07-23 03:16 UTC, pistoia commented on docs/index.rst
> +   with quantum computing for quantum chemistry problem. Is a set of tools, algorithms
problem --> **problems**

2019-07-23 03:17 UTC, pistoia commented on docs/index.rst
> +   with quantum computing for quantum chemistry problem. Is a set of tools, algorithms
Is a set of tools --> **Qiskit Chemistry** is a set of tools

2019-07-23 03:18 UTC, pistoia commented on docs/index.rst
> +   interfaces prebuilt for the following four computational chemistry software drivers:
the following four **classical** computational chemistry software drivers

2019-07-23 03:19 UTC, pistoia commented on docs/index.rst
> +   financial analysis and optimization experiments and contribute to the quantum
financial analysis --> financial-analysis

2019-07-23 03:20 UTC, pistoia commented
@SooluThomas thank you for improving the Qiskit documentation.  I have embedded a few comments.  Please feel free to reach out to me if you have any questions.  Thank you.

2019-07-23 15:53 UTC, lzdanski submitted a review, later dismissed
@SooluThomas This looks GREAT overall! Much easier to read. I have a number of comments around some of the wording/formatting. There are two files, `aqua/library` and `ignis/index` that I want to take a closer look at, so I didn't add any suggestions there. I'll make a separate PR for it.

2019-07-23 15:53 UTC, lzdanski commented on docs/aer/index.rst
> +A high performance simulator framework for quantum circuits
```suggestion

```

2019-07-23 15:53 UTC, lzdanski commented on docs/aer/index.rst
> +Qiskit Aer provides a high performance simulator framework for the Qiskit software stack. It
I don't think we need that one line intro anymore. It doesn't quite make sense in this context, and then we repeat it in the next section. Also, this paragraph has a run-on sentence I tidied up a little. 

```
Qiskit Aer provides a high performance simulator framework for quantum circuits using the Qiskit 
software stack. It contains optimized C++ simulator backends for executing circuits compiled in 
Qiskit Terra. Aer also provides tools for constructing highly configurable noise models for 
performing realistic noisy simulations of the errors that occur during execution on real devices.
```

2019-07-23 15:53 UTC, lzdanski commented on docs/aqua/library.rst
> +2. **Novel Features**: In addition to its modularity and extensibility,
This section gives a great overview of the different features, but the voice is more like release notes than documentation. I'll make a separate PR for this section.

2019-07-23 15:53 UTC, lzdanski commented on docs/index.rst
> +Certainly, a central goal of Qiskit is to build a software stack
```suggestion
A central goal of Qiskit is to build a software stack
```

2019-07-23 15:53 UTC, lzdanski commented on docs/index.rst
> +Qiskit allows the user to easily design experiments and run them on simulators and real
```suggestion
You can use Qiskit to easily design experiments and run them on simulators and real
```

2019-07-23 15:53 UTC, lzdanski commented on docs/index.rst
> +Qiskit consists of four foundational elements:  Terra (the code foundation,
This section would be more readable as a bullett list:

```
Qiskit consists of four foundational elements.

  * **Terra**: Composing quantum programs at the level of circuits and
  pulses with the code foundation
  * **Aqua**: Building algorithms and applications
  * **Ignis**: Addressing noise and errors
  * **Aer**: Accelerating development via simulators, emulators, and debuggers
```

2019-07-23 15:53 UTC, lzdanski commented on docs/index.rst
> +   of quantum computers we need better simulators, emulators and debuggers.  Aer will help
```suggestion
   of quantum computers we need better simulators, emulators and debuggers.  Aer helps
```

2019-07-23 15:53 UTC, lzdanski commented on docs/terra/index.rst
> +Qiskit Terra is organized in this `repo <https://github.com/Qiskit/qiskit-terra>`_.
```suggestion
Qiskit Terra is organized in the qiskit-terra `repo <https://github.com/Qiskit/qiskit-terra>`_.
```

2019-07-23 15:53 UTC, lzdanski commented on docs/terra/index.rst
> +directory, and test scripts are located in `test <https://github.com/Qiskit/qiskit-terra/tree/master/test>`_.
```suggestion
directory, and test scripts are located in the `test <https://github.com/Qiskit/qiskit-terra/tree/master/test>`_ directory.
```

2019-07-25 17:21 UTC, derivation requested changes
- [x] Please revert all changes to the Rewiring Circuits section (all subfolders, subfiles).
- [x] Consider merging info in Qiskit Chemistry index and Overview pages

2019-07-25 17:21 UTC, derivation commented on docs/aqua/chemistry/qiskit_chemistry.rst
> +   :hidden:
Why isn't the Overview merged into this file?

2019-07-25 17:21 UTC, derivation commented on docs/terra/transpiler/about/index.rst
> +.. _Transpiler API Overview:
Please revert all changes to the Rewiring Circuits section.

2019-07-25 17:24 UTC, derivation commented
@SooluThomas after responding to my review, open up a new issue (independent of this PR) that calls for standardizing the info architecture across the landing pages (index.rst).

2019-07-25 17:26 UTC, SooluThomas commented on docs/aqua/chemistry/qiskit_chemistry.rst
> +   :hidden:
There was a lot of information in Qiskit Chemistry overview and also, index.rst can't have subsections because that will mess up the existing toc.

2019-07-26 19:26 UTC, derivation approved these changes

2019-07-26 23:16 UTC, merged