Add single-threaded versions of quantum volume and RB benchmarks.
Qiskit/qiskit-metapackage pull request #396
Opened 2019-08-08 19:54 UTC by kdk

`qiskit.transpile` will attempt to distribute circuits for transpilation across any available cores, generally reducing transpile times, but measuring single threaded performance can provide more reliable insight into how individual commits impact performance and will allow for measuring the benefit of parallel vs serial transpilation.

This PR adds a single-threaded version to the two benchmarks which currently transpile in parallel, RB and quantum_volume, by hard coding the `QISKIT_IN_PARALLEL` environment variable.

2019-08-08 20:01 UTC, mtreinish requested changes
The idea behind this change LGTM, but I'm concerned about the environmental variable use here. Will the variable stick between runs of the benchmark? I think just to be safe we should add a `teardown`[1] method to both benchmark classes to make sure we unset the env variable (if it's set) after each benchmark execution.

[1] https://asv.readthedocs.io/en/stable/writing_benchmarks.html#setup-and-teardown-functions

2019-08-13 11:58 UTC, jaygambetta commented
@mtreinish did you and @kdk close on this.

2019-08-14 19:24 UTC, mtreinish commented
@jaygambetta @kdk and I were talking about this one the other day. There are some last minute changes he was working on before this is ready.

2019-08-15 13:45 UTC, mtreinish approved these changes

2019-08-18 13:42 UTC, merged