Added doc to Aer under /docs/aer
Qiskit/qiskit-metapackage pull request #41
Opened 2019-01-15 19:58 UTC by derivation

### Summary
Added doc to Aer under /docs/aer

### Details and comments
1. The .ipynb files are used to generate the associated .rst files with nbsphinx, called automatically by the command 'make doc'.
2. Changed /docs/conf.py to use the nbsphinx module to convert Jupyter notebooks into RST files.
3. Updated docs/theme/_templates/layout.html to include Aer in the top navigation

2019-01-15 19:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=41) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=41) before we can accept your contribution.<br/><hr/>**Paul Kassebaum** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=41) it.</sub>

2019-01-15 19:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=41) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=41) before we can accept your contribution.<br/><hr/>**Paul Kassebaum** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=41) it.</sub>

2019-01-16 02:27 UTC, jaygambetta commented
please remove juypter notebooks.

2019-01-17 20:53 UTC, derivation commented
- removed the Jupyter notebooks from /docs/aer/ via .gitignore
- now using nbconvert instead of nbsphinx to go from IPYNB to RST

2019-01-23 13:32 UTC, jaygambetta commented
@chriseclectic could you review this.

2019-01-24 04:30 UTC, chriseclectic commented
@jaygambetta yes, it might take a couple days to go through it though while I'm traveling

2019-01-24 16:13 UTC, chriseclectic requested changes

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/simulate_operator_form.rst
> +Find the Operator Form of a Circuit
This should be find the unitary matrix for a circuit

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/simulate_operator_form.rst
> +ideal (noise free) Qiskit Terra™ circuits.
Don't say `ideal (noise free)` in these documents, a normal circuit in terra is noise free.

Instead explicitly say `noisy` for the cases where we are simulating with a noise model

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/simulate_operator_form.rst
> +    from qiskit.tools.visualization import plot_histogram, plot_state_city
`from qiskit.tools.visualization import plot_histogram, plot_state_city` isnt needed for unitary simulator

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/simulate_statevectors.rst
> +    from qiskit.tools.visualization import plot_histogram, plot_state_city
`plot_histogram` isn't needed for statevector simulator

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/index.rst
> +   Overview <overview>
There should be a detailed `installing` section, that includes a more readable version of the detailed build from source instructions in the `contributing` doc of qiskit-aer repo (and then these can be removed from that doc and the main qiskit-aer readme can point here for detailed install instructions).

It should include:
* Composite package: `pip install qiskit`
* Installing aer separately `pip install qiskit-aer`
* Upgrading aer separately to main package: `pip install qiskit-aer --upgrade`
* Building from source instructions organised into detailed instructions for:
  * Linux (ubuntu, redhat/centOS, maybe other distros)
  * MacOS (basic XCode,  XCode + OpenMP, GCC builds)
  * Windows (probably 7 and 10)

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/getting_started_with_qiskit_aer.rst
> +| :doc:`Make measurements <simulate_measurements>`
This should just be called `Simulate an experiment`

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/release_history.rst
> +Qiskit Aer 0.1.0
This section needs some work. I don't know if you should go into quite as much detail as is here on the individual backends, I would make it much shorter. It should also mention noise module.

Something like

Version 0.1.0

* Aer provider:
  * QasmSimulator: simulate an experiments and return measurement outcomes.
  * StatevectorSimulator: return the final statevector for a quantum circuit acting on the all zero state
  * UnitarySimulator: return the unitary matrix for a quantum circuit
* noise module:
  * NoiseModel, QuantumError, ReadError classes for building quantum errors
  * Standard errors module including functions for generating QuantumError objects for kraus errors, mixed unitary errors, ... (etc)
  * Device noise module for automatically generating a noise model for a device from device BackendProperties
* utils module:
  * qobj_utils containing functions for directly modifying a qob to insert special simulator instructions not yet supported through the terra API

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/simulate_measurements.rst
> +Make Measurements on a Circuit
Simulating an experiment

2019-01-24 16:13 UTC, chriseclectic commented on docs/aer/simulate_measurements.rst
> +simulations of (noise free) Qiskit Terra™ circuits.
This tutorial demonstrates how to use Qiskit Aer to simulate execution of quantum circuits and return the measurement outcomes for the experiment.

Also do we need these Tms (they look weird)

2019-01-25 18:48 UTC, derivation commented on docs/aer/index.rst
> +   Overview <overview>
I took a shot at writing this. I was intentionally redundant in the Linux and macOS sections to let readers have a continuous flow of reading, rather than jumping back and forth, which was my experience when I first used the `contributing` install instructions for macOS. 

I'm not sure what details should be included in the Windows instructions.

2019-01-25 18:53 UTC, derivation commented on docs/aer/simulate_measurements.rst
> +simulations of (noise free) Qiskit Terra™ circuits.
Based on my experience working with the marketing legal department at my prior company, if we don't consistently put a TM mark on our trademarks at least once in a given context (e.g. a single scrollable webpage), then we could lose a claim of ownership of the mark to another party.

Nonetheless, I took out unnecessary references to our other trademarked names, keeping it down to just one if possible, because I agree it looks weird.

2019-01-28 21:12 UTC, chriseclectic commented on docs/aer/device_noise_simulation.rst
> +        ('cx', [13, 1], 2286), ('cx', [13, 12], 1504), ('cx', [], 800)
I think the empty brackets is a typo in my original tutorial. I need to double check it.

2019-01-28 21:14 UTC, chriseclectic commented on docs/aer/installing_aer.rst
> +  $ sudo apt install libopenblas-dev
I think you need to install the `build-essentials` to get the compilers/blas etc.

2019-01-28 21:16 UTC, chriseclectic commented on docs/aer/installing_aer.rst
> +We recommend installing **OpenBLAS**, which is our default choice:
I think Accelerate framework that comes with xcode works fine if you don't install OpenBLAS, so it should be the minimal (easiest) choice. But double check with @atilag

2019-01-28 21:16 UTC, chriseclectic commented on docs/aer/installing_aer.rst
> +  qiskit-aer$ python ./setup.py bdist_wheel -- -DCMAKE_VARIABLE=Values -- -Makefile_or_VisuaStudio_Flag
VisualStudio flag is for windows

2019-02-03 21:08 UTC, jaygambetta commented on .gitignore
> +docs/**/*.ipynb
this change does not need to be made

2019-02-03 21:15 UTC, jaygambetta commented on docs/aer/getting_started_with_qiskit_aer.rst
> +|
why do we need this file? Can't we just go directly in the index file.

2019-02-12 14:51 UTC, derivation commented on docs/aer/release_history.rst
> +Qiskit Aer 0.1.0
I rewrote this using Chris' notes from our Monday IBM Q Software Talks meeting.

2019-02-12 14:59 UTC, derivation commented on docs/aer/installing_aer.rst
> +We recommend installing **OpenBLAS**, which is our default choice:
@atilag , what do think? To install Aer from source, would a user need to install OpenBLAS explicitly, or is the Accelerate framework that comes with Xcode already sufficient?

2019-02-12 15:06 UTC, diego-plan9 commented on docs/aer/device_noise_simulation.rst
> +.. image:: device_noise_simulation_files/device_noise_simulation_9_0.png
For consistency with the latest changes, can you move all images to `docs/images/figures`, and update the `... image::` paths accordingly?

2019-02-12 15:11 UTC, derivation commented on docs/aer/installing_aer.rst
> +  $ sudo apt install libopenblas-dev
Looks like you're right, but it's the singular `build-essential`. I'll make the change in the text.

2019-02-12 15:21 UTC, derivation commented on docs/aer/release_history.rst
> +Qiskit Aer 0.1.0
I rewrote this based on Chris' IBM Q Software Talks presentation

2019-02-12 15:28 UTC, derivation commented on docs/aer/index.rst
> +   Overview <overview>
@chriseclectic I'm not familiar with Windows development tools and workflows. Do you know who would be able to write a Windows specific walk-though to build from source?

2019-02-12 15:40 UTC, derivation commented on docs/aer/getting_started_with_qiskit_aer.rst
> +|
I was trying to emulate this design: https://www.mathworks.com/help/matlab/getting-started-with-matlab.html

which lets users read a little blurb about each individual tutorial before clicking into it. This is helpful for scanning for just the material you really need. 

Ideally, the design would also keep the global ToC at a depth of only ~2-3 levels. However, I haven't yet figured out how to keep the global ToC from including these tutorials while retaining the handy next/last page links at the bottom.

Would you like me to scrap this design and simply use the index file to point to these tutorials?

2019-02-12 15:44 UTC, derivation commented on docs/aer/device_noise_simulation.rst
> +.. image:: device_noise_simulation_files/device_noise_simulation_9_0.png
@diego-plan9 I think this begs a bigger question: will tutorials be authored using Jupyter notebooks? This RST file was generated from a Jupyter notebook via nbconvert, which automatically generates the image directory structure you see referenced here.

2019-02-12 22:45 UTC, jaygambetta commented on docs/aer/getting_started_with_qiskit_aer.rst
> +|
I don't have a view either way. If this is what you want to go I am good with this but can we also do it to terra. 

I am going to merge so that we have got it in the documentation. But can you think about which way you want to go and then make an issue and either change terra or aer so they look the same? Unification is important.

2019-02-12 22:45 UTC, merged

2019-02-13 17:31 UTC, diego-plan9 commented on docs/aer/device_noise_simulation.rst
> +.. image:: device_noise_simulation_files/device_noise_simulation_9_0.png
I think Jay can provide more info, but the idea is that the initial version (ie. the one you pushed) is based off the tutorials, but after that they evolve separately - no worries!

2019-02-13 17:38 UTC, jaygambetta commented on docs/aer/device_noise_simulation.rst
> +.. image:: device_noise_simulation_files/device_noise_simulation_9_0.png
yeah, they have different goals and will diverge.

2019-02-13 18:07 UTC, derivation commented on docs/aer/getting_started_with_qiskit_aer.rst
> +|
Okay. I'll aim for consistency across the elements.

2019-02-13 18:10 UTC, derivation commented on docs/aer/device_noise_simulation.rst
> +.. image:: device_noise_simulation_files/device_noise_simulation_9_0.png
Okay. For now, I'll make sure the images in these Aer tutorials pull from `docs/images/figures`.