Refactor master clone logic and set content_prefix to poBranch
Qiskit/qiskit-metapackage pull request #661
Opened 2019-11-01 19:38 UTC by SooluThomas

### Summary

Edits made to poBranch

### Details and comments

2019-11-01 19:42 UTC, SooluThomas commented
"on hold" because waiting for #634 to be completed and merged

2019-11-01 19:43 UTC, delapuente requested changes

2019-11-01 19:43 UTC, delapuente commented on tools/deploy_documentation.sh
> +mv docs_source/docs/ $SOURCE_DIR/docs/
I think this is `mv docs_source/docs $SOURCE_DIR`

2019-11-01 19:43 UTC, delapuente commented on tools/deploy_documentation.sh
> +cp -r $SOURCE_DIR/docs/locale docs_source/docs
Adds a slash at the end of `docs`.

2019-11-01 21:12 UTC, delapuente approved these changes
I'm fine with this but let's wait for @mtreinish for another look.

2019-11-01 21:32 UTC, mtreinish commented on tools/deploy_documentation.sh
> +mv docs_source/docs/ $SOURCE_DIR
Is the point of this to do the equivalent of `rsync --exclude=locale --delete docs_source/docs/ $SOURCE_DIR/docs/` just using cp, rm, and mv? (ie to delete files that have been removed from master's docs) I'd honestly feel more comfortable using either rclone for this since we already have it installed for the upload and it mirrors the rsync mechanics. You can probably just replace these 3 lines with:

`rclone -v --exclude='locale/**' sync docs_source/docs docs/`

That way we can see when it deletes something or makes any other changes.

If you'd like to keep it like this I think we should at least add a comment here about the purpose of this section, because it few seconds to figure out the purpose of this.

2019-11-01 21:32 UTC, mtreinish commented on tools/deploy_documentation.sh
> +parallel sphinx-build -b html -D content_prefix=documentation -D language={} . _build/html/locale/{} ::: $TRANSLATION_LANG
Where does `content_prefix` come from? I can't find it in the sphinx documentation

2019-11-01 23:06 UTC, delapuente commented on tools/deploy_documentation.sh
> +parallel sphinx-build -b html -D content_prefix=documentation -D language={} . _build/html/locale/{} ::: $TRANSLATION_LANG
It is in our extension, to support the generation of the base urls for our translated and stable versions.

2019-11-01 23:07 UTC, delapuente commented on tools/deploy_documentation.sh
> +mv docs_source/docs/ $SOURCE_DIR
Right! It is `rsync`. We can use `rclone`.

2019-11-04 22:31 UTC, mtreinish approved these changes

2019-11-04 22:31 UTC, mtreinish commented on tools/deploy_documentation.sh
> +rclone sync -v --exclude='locale/**' docs_source/docs docs/
Rclone has implicit trailing slashes coming from rsync: https://rclone.org/commands/rclone_copy/

```suggestion
rclone sync -v --exclude='locale/**' docs_source/docs docs
```

2019-11-08 08:00 UTC, merged