Test/rtd
Qiskit/qiskit-metapackage pull request #662
Opened 2019-11-01 19:52 UTC by delapuente

### Summary
Change the theme of documentation to Read the Docs (https://sphinx-rtd-theme.readthedocs.io/en/stable/)

### Details and comments
It also adds support for multiple languages, multiple versions (although it will be disabled right now), and include metrics.

2019-11-01 20:54 UTC, SooluThomas commented on docs/theme/versions.html
> +</div>
```suggestion
</div>

```
Adding new line to the end of file

2019-11-01 20:54 UTC, SooluThomas commented on docs/versionutils.py
> +        return [table_node] + messages
```suggestion
        return [table_node] + messages
        
```
Adding new line to the end of file

2019-11-04 22:38 UTC, mtreinish requested changes
The sphinx conf.py, extension changes, and the deploy_documentation and tox changes all look fine to me from a quick glance. But I built things locally and the theme configuration (I expect probably a css thing) don't look quite right to me. For example:

![Screenshot_2019-11-04_17-32-59](https://user-images.githubusercontent.com/2447371/68163926-8e70a600-ff29-11e9-939a-78d674d05d2d.png)
![Screenshot_2019-11-04_17-33-59](https://user-images.githubusercontent.com/2447371/68163929-903a6980-ff29-11e9-8898-de39ac7a676d.png)

Everything is monospaced font except for code sections (which seems like the opposite of expectations).

Also one thing I like that @nonhermitian did for the terra docs builds (and something I've copied to aer and ignis) which is also using the RTD theme is having the qiskit logo in the upper left hand corner at the top of the side bar. For example:

![Screenshot_2019-11-04_17-37-36](https://user-images.githubusercontent.com/2447371/68164029-d0015100-ff29-11e9-8626-a42e059de957.png)

Maybe you should copy that from what terra has in it's local sphinx config.

2019-11-05 10:57 UTC, delapuente commented
You're right. This is happening in Safari. Let's find the cause and fix it. I'm delaying adding the Qiskit Logo (which personally I think it is a great idea) to the follow up #663

2019-11-05 15:18 UTC, SooluThomas commented on docs/versionutils.py
> +    base = '/locale/%s' % code if code else ''
For pointing towards correct localized documentation, 
```suggestion
    base = '/documentation/locale/%s' % code if code else ''
```

2019-11-05 15:26 UTC, delapuente commented on docs/versionutils.py
> +    base = '/locale/%s' % code if code else ''
This is done by `_get_url` which is in charge of adding the content prefix.

2019-11-05 15:36 UTC, SooluThomas commented on docs/versionutils.py
> +    base = '/locale/%s' % code if code else ''
This has been taken care of in PR #661 [(change)](https://github.com/Qiskit/qiskit/pull/661/files#diff-b14ef4cdb78e1df5c71a1851ccd8f4efR39)

2019-11-05 15:37 UTC, SooluThomas submitted a review, later dismissed

2019-11-05 18:11 UTC, mtreinish reviewed
This looks better to me, the issues I outlined in the last review look like they're fixed now. I have one thing inline that we should change but I think this will be good to merge after that. I'm not a big fan of the color scheme I like what the terra docs do right now with the rtd theme:. But colors (and icons) are easy enough to iterate on post-merge and making the switch with all the widgets reimplemented is a big enough change on it's own.

2019-11-05 18:11 UTC, mtreinish commented on docs/conf.py
> +    'display_github': True,
I don't think we should do this actually. The edit on github button would be useful if the files contained details but since most of what we have is autodoc you end up at files like: https://github.com/Qiskit/qiskit/blob/master/docs/apidoc/execute.rst which don't really have the contents. Then after #551 merges the files won't even exist in Qiskit/qiskit anymore.

2019-11-05 18:11 UTC, mtreinish reviewed
This looks better to me, the issues I outlined in the last review look like they're fixed now. I have one thing inline that we should change but I think this will be good to merge after that. I'm not a big fan of the color scheme I like what the terra docs do right now with the rtd theme:. But colors (and icons) are easy enough to iterate on post-merge and making the switch with all the widgets reimplemented is a big enough change on it's own.

2019-11-05 19:10 UTC, mtreinish reviewed
Sorry to keep finding one issue at a time, but I just realized that the version dropdown will have a pretty big problem as we move into the future. See inline

2019-11-05 19:10 UTC, mtreinish commented on docs/theme/versions.html
> +      {% for version in version_list %}
This is actually a problem. Looking at how this is built at https://github.com/Qiskit/qiskit/pull/662/files#diff-95b277ed16282648f055393de56680cfR44 we can't do this statically with a build time variable. The build time list that we get from git is out of date the day we push a new tag. For example, when we add this when we push a 0.14.0 tag the statically hosted build we already uploaded for 0.13.0 won't have 0.14.0 in it's version_list variable. We need a way of getting the version info from a single source that we update independently of the individual doc build. For example we could have a static js file we continually update at `documentation/versions.js` that has the list or something, then make the theme search for that file off a relative url and display the version switcher from that data if that's present. As of right now we'll end up with a newer versions that aren't reachable from older versions which is less than ideal.

2019-11-05 19:12 UTC, delapuente commented on docs/theme/versions.html
> +      {% for version in version_list %}
Yes, this is under the radar and @SooluThomas and I were discussing how to do it. Let's go and merge this one and we can start finding a solution for that and other version-related issues.

2019-11-05 19:31 UTC, delapuente commented on docs/theme/versions.html
> +      {% for version in version_list %}
A couple of solutions would be:
1. Use a daily build to check if there is some tag missing, and if so, trigger a deployment.
2. [Deploy on tag](https://docs.travis-ci.com/user/deployment-v2/conditional#tag).
3. A combination of both.

2019-11-06 09:10 UTC, delapuente commented
Per offline conversations, getting the list of updated versions could be worked around. The real problem with static generation is that, if avoiding regenerating everything, every time a new version is added (i.e., building the latest one only), documentation for old versions would not get the list of new ones preventing the user from navigating to the latest version from a previous one.

2019-11-06 09:12 UTC, delapuente commented
@mtreinish @SooluThomas the latest commit remove everything related to versions. Translations can remain static until multi-version is added. A review is needed.

2019-11-06 15:58 UTC, SooluThomas approved these changes

2019-11-07 22:18 UTC, mtreinish approved these changes
I think this LGTM. I tested a local build and everything looks good. I still think there are some small style things to fix, but that's easy to do in a follow-up. Thanks for updating it to address my earlier concerns.

2019-11-07 23:14 UTC, mtreinish commented
I held off on merging this because of #664. Without a fix for that the documentation will become a blackhole from qiskit.org once people click on it. We should at least have a solution identified for that so we can push a quick follow up to this and minimize the amount of time things are in that state

2019-11-07 23:15 UTC, mtreinish commented
> I think this LGTM. I tested a local build and everything looks good. I still think there are some small style things to fix, but that's easy to do in a follow-up.

I wrote a patch for this on top of this branch here: https://github.com/mtreinish/qiskit/commit/d6bb3bd08e6861585443b920e82e8117ff23efad I'll push a PR with it as soon as we merge this.

2019-11-08 07:57 UTC, merged

2019-11-08 07:58 UTC, delapuente commented
Thank you very much @SooluThomas and @mtreinish