Added better navigation to different elements under Installation from source section.
Qiskit/qiskit-metapackage pull request #691
Opened 2019-11-17 10:05 UTC by melvin2016

Fixes #690
### Summary
Added better navigation to different elements under Installation from Source section.

2019-11-17 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=691) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=691) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=691) it.</sub>

2019-11-17 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=691) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=691) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=691) it.</sub>

2019-11-18 14:35 UTC, derivation requested changes
Thank you for contributing. Because the docs get translated into multiple languages, it's best to use the `:ref:` technique rather than rely on the names of sections, which will change from language to language. Here's an example of the `:ref:` syntax:

`.. _my-reference-label:`

`Section to cross-reference`
`--------------------------`

`This is the text of the section.`

``It refers to the section itself, see :ref:`my-reference-label`.``

2019-11-18 16:25 UTC, melvin2016 commented
Ok i will make the changes.

On Mon, 18 Nov, 2019, 20:05 Paul Kassebaum, <notifications@github.com>
wrote:

> *@derivation* requested changes on this pull request.
>
> Thank you for contributing. Because the docs get translated into multiple
> languages, it's best to use the :ref: technique rather than rely on the
> names of sections, which will change from language to language. Here's an
> example of the :ref: syntax:
>
> .. _my-reference-label:
>
> Section to cross-reference
> --------------------------
>
> This is the text of the section.
>
> It refers to the section itself, see :ref:`my-reference-label`.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Qiskit/qiskit/pull/691?email_source=notifications&email_token=AFJL24WWSMIY4VKLEDS2ZXTQUKR4NA5CNFSM4JOJDEN2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCL5AHHI#pullrequestreview-318374813>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFJL24XQDQQTFXSK7OSPCHLQUKR4NANCNFSM4JOJDENQ>
> .
>

2019-11-19 16:49 UTC, melvin2016 commented
> Thank you for contributing. Because the docs get translated into multiple languages, it's best to use the `:ref:` technique rather than rely on the names of sections, which will change from language to language. Here's an example of the `:ref:` syntax:
> 
> `.. _my-reference-label:`
> 
> `Section to cross-reference`
> `--------------------------`
> 
> `This is the text of the section.`
> 
> `` It refers to the section itself, see :ref:`my-reference-label`. ``

Thank You for pointing out the mistake. I had made the changes.
@derivation

2019-11-19 17:10 UTC, derivation requested changes
Thank you. Could you prepend the word 'install' to the :ref: labels (e.g. _install-qiskit-terra) to increase the likelihood that the labels will be unique across the entire doc? The :ref: references work across all of the doc files, not just within a single file.

2019-11-19 17:38 UTC, SooluThomas commented on docs/contributing_to_qiskit.rst
> +#. qiskit-ibmq-provider - :ref:`qiskit-ibmq-provider` (if wanting to connect to the IBM Q devices or online
I'd also suggest using 
```
#. :ref:`qiskit-terra <qiskit-terra>`
#. :ref:`install-qiskit-aer <qiskit-aer>`
#. :ref:`install-qiskit-ignis <qiskit-ignis>`
#. :ref:`install-qiskit-aqua <qiskit-aqua>`
#. :ref:`install-qiskit-ibmq-provider <qiskit-ibmq-provider>` 
```
so that the output generates the same old thing with hyperlinks.

2019-11-19 18:31 UTC, melvin2016 commented on docs/contributing_to_qiskit.rst
> +#. qiskit-ibmq-provider - :ref:`qiskit-ibmq-provider` (if wanting to connect to the IBM Q devices or online
Yeah this seems more friendly. Adding this.
I think the order is vice-versa 
`#. :ref:`qiskit-terra <install-qiskit-terra>``
 instead of 
`#. :ref:`install-qiskit-terra <qiskit-terra>``.

2019-11-19 18:32 UTC, melvin2016 commented
@SooluThomas @derivation pushed a commit with proposed changes.

2019-11-19 18:47 UTC, derivation submitted a review, later dismissed

2019-11-19 18:48 UTC, derivation approved these changes

2019-11-19 18:49 UTC, derivation commented
Thanks for your help, @melvin2016

2019-11-19 18:54 UTC, merged