Added docs for mcmt gate
Qiskit/qiskit-metapackage pull request #71
Opened 2019-02-07 23:25 UTC by tigerjack

### Summary
Added documentation for the `Aer` `mcmt` gate as per https://github.com/Qiskit/qiskit-aqua/pull/341

### Details and comments

2019-02-07 23:25 UTC, tigerjack commented
@hushaohan here.

2019-02-07 23:50 UTC, hushaohan requested changes
a couple of minor points

2019-02-07 23:50 UTC, hushaohan commented on docs/aqua/algorithms.rst
> +    allows to generalize a single-control, single-target gate (such as `cz` to
the opening `(` isn't closed?

2019-02-07 23:50 UTC, hushaohan commented on docs/aqua/algorithms.rst
> +    employs the same strategy adopted for the basic mode of `mct`, i.e.
almost "the same": the basic `mct` uses `n-2` ancilla as it uses a `ccx` to write to the target rather than a `cx`

2019-02-08 09:18 UTC, tigerjack commented on docs/aqua/algorithms.rst
> +    employs the same strategy adopted for the basic mode of `mct`, i.e.
@hushaohan ok I'll modify it, adding some other comments. It was late here yesterday :D

2019-02-08 11:39 UTC, hushaohan approved these changes

2019-02-08 11:44 UTC, hushaohan commented
@tigerjack thx for addressing my comments!

2019-02-08 14:37 UTC, merged