Fix code quality issue
Qiskit/qiskit-metapackage pull request #739
Opened 2019-12-15 11:20 UTC by sauravsrijan

### Summary
Changes:
- Remove redundant call to `list()` on a list comprehension
- Add .deepsource.toml file to run continuous static analysis on the repository with DeepSource

### Details and comments
No new tests are required for the changes in this PR.

This PR additionally adds `.deepsource.toml` configuration file to run static analysis continuously on the repo with DeepSource. Upon enabling DeepSource, quality and security analysis will be run on every PR to detect 500+ types of problems in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.

DeepSource is free to use for open-source projects, and is used by teams at NASA, Uber, Slack among many others, and open-source projects like ThoughtWorks/Gauge, Masonite Framework, etc.

To enable DeepSource analysis after merging this PR, please follow these steps:

- [Sign up](http://deepsource.io/signup) on DeepSource with your GitHub account and grant access to this repo.
- Activate analysis on this repo [here](https://deepsource.io/dashboard/gh/Qiskit/activate-repo/).
- You can also look at the [docs](https://deepsource.io/docs) for more details. Do let me know if I can be of any help!

2019-12-15 11:20 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=739) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=739) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=739) it.</sub>

2019-12-15 11:20 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=739) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=739) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=739) it.</sub>

2020-03-09 18:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=739) <br/>All committers have signed the CLA.

2020-03-09 19:59 UTC, mtreinish requested changes
Hi, while you seem passionate about your service we're not really interested in using it. We have sufficient code style checkers and CI testin already in place on this repo. The file you're changing here is just an ancillary script that's used as part of the release process and not covered by that.

If you would like to remove the config file and just have his PR fix the no-op list cast, that change by itself would be good to merge. Otherwise we can just close this PR.

2020-03-11 15:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=739) <br/>All committers have signed the CLA.

2020-04-30 01:53 UTC, nonhermitian commented
Closing as we are not going to use the service and discussion is stale.

2020-04-30 01:53 UTC, closed without merging