fix typo in files under docs and test
Qiskit/qiskit-metapackage pull request #751
Opened 2019-12-22 06:51 UTC by kiszk

### Summary

Fix typo and spelling in rst files under `docs` directory and in python file under `test` directory

### Details and comments

2020-01-27 20:38 UTC, mtreinish requested changes
Looking solely at the `test/benchmarks/passes.py` file this lgtm. Catching the 2 typos on `peakmem` adds 2 benchmarks that haven't been running (`peakmem_` is a prefix for the benchmark suite telling it how to run the benchmark). However as noted inline one typo I think we have to live with for the time being otherwise we'll invalidate the historical data already built for that benchmark.

2020-01-27 20:38 UTC, mtreinish commented on test/benchmarks/passes.py
> +    def peakmem_resource_optimization(self, _, __):
While I agree this is a typo changing this would invalidate the history of results for this benchmark hosted at:

https://qiskit.github.io/qiskit/#passes.PassBenchmarks.peakmem_resoure_optimization

I think weighing a typo correction vs having to lose the historical data we should just leave the typo.

2020-01-30 13:46 UTC, kiszk commented on test/benchmarks/passes.py
> +    def peakmem_resource_optimization(self, _, __):
@mtreinish Thank you for letting me know the important information. I did not know it. I totally agree with reverting changes in `passes.py`.

2020-01-30 14:13 UTC, mtreinish commented on test/benchmarks/passes.py
> +    def peakmem_resource_optimization(self, _, __):
@kiszk thanks for updating, but you reverted a bit too much in the latest revision. Doing the s/peakemem/peakmem/g replacement was the correct thing to do.

The only thing which I was saying we shouldn't change was `s/resoure_optimization/resource_optimization/g` because of the historical tracking. If you could add back the original `peakemem` fixes then I'll be good with this. Thanks.

2020-01-30 14:42 UTC, mtreinish submitted a review, later dismissed
Thanks for updating, this LGTM

2020-04-25 03:26 UTC, jaygambetta approved these changes

2020-04-30 11:37 UTC, mtreinish approved these changes

2020-04-30 20:14 UTC, merged