Add Qiskit Pulse Benchmarks
Qiskit/qiskit-metapackage pull request #848
Opened 2020-03-16 17:30 UTC by SooluThomas

### Summary

Partially fixes #794.

Schedule construction benchmarks:
- with parameters being the:
   - [ ] number of unique pulses
   - [ ] number of channels
   - [x] ~number of uses of each pulse~
- options:
   - pulse types:
      - [ ] Parametric
      - [ ] Sample
   - Building methods:
      - [ ] Append instruction
      - [ ] Insert instruction right to left
      - [ ] Convert the instruction to a schedule and then take the union of all schedules.  

### Details and comments

2020-03-17 15:54 UTC, lcapelluto commented on test/benchmarks/pulse/schedule_construction.py
> +# (C) Copyright IBM 2018, 2019.
```suggestion
# (C) Copyright IBM 2020.
```

2020-03-17 16:04 UTC, lcapelluto requested changes

2020-03-17 16:04 UTC, lcapelluto commented on test/benchmarks/pulse/schedule_construction.py
> +    my_pulse = SamplePulse(np.random.random(50),
probably `np.random` is fast, but maybe we can hardcode this array so that we avoid including `np.random` in our benchmark of Pulse.

2020-03-17 16:04 UTC, lcapelluto commented on test/benchmarks/pulse/schedule_construction.py
> +
For these short functions, I don't think a new line before the return is necessary. It will help the eye collect 3 short, separate functions if there is less vertical space within each.

2020-03-17 16:04 UTC, lcapelluto commented on test/benchmarks/pulse/schedule_construction.py
> +    return (build_schedule(my_pulse,
superfluous parens here and below

2020-03-17 16:04 UTC, lcapelluto commented on test/benchmarks/pulse/schedule_construction.py
> +    my_pulse = SamplePulse(np.random.random(50),
I see now it looks like it's only called in `setup`. Up to you then!

2020-03-17 16:04 UTC, lcapelluto commented on test/benchmarks/pulse/schedule_construction.py
> +        if self.parametric_sched.stop_time >= self.sample_sched.start_time:
sample sched start time will always be 0, right?

2020-03-17 16:04 UTC, lcapelluto commented on test/benchmarks/pulse/schedule_construction.py
> +    params = ([1, 2, 5], [8, 128, 2048])
I might be misunderstanding how these are used. It looks like these will only affect the size of the schedules that are set up, but it won't affect the anticipated runtime of `append` and `insert`. Is that right?

2020-03-17 16:08 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +        if self.parametric_sched.stop_time >= self.sample_sched.start_time:
In this case, yes.

2020-03-17 16:17 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +    params = ([1, 2, 5], [8, 128, 2048])
afaik, it would affect the runtime if I increase the params values. 

currently, 

```
[ 25.00%] ··· pulse.schedule_construction.ScheduleConstructionBench.time_append_instruction                                                                                                                                                 ok
[ 25.00%] ··· ========================= ========= ========== ==========
              --                               number_of_channels      
              ------------------------- -------------------------------
               number_of_unique_pulses      8        128        2048   
              ========================= ========= ========== ==========
                          1              182±0μs   2.30±0ms   45.2±0ms 
                          2              296±0μs   3.17±0ms   69.2±0ms 
                          5              332±0μs   5.47±0ms   89.0±0ms 
              ========================= ========= ========== ==========

[ 50.00%] ··· pulse.schedule_construction.ScheduleConstructionBench.time_insert_instruction_left_to_right                                                                                                                                   ok
[ 50.00%] ··· ========================= ========= ========== ==========
              --                               number_of_channels      
              ------------------------- -------------------------------
               number_of_unique_pulses      8        128        2048   
              ========================= ========= ========== ==========
                          1              260±0μs   2.78±0ms   47.3±0ms 
                          2              337±0μs   4.46±0ms   87.4±0ms 
                          5              836±0μs   11.1±0ms   214±0ms  
              ========================= ========= ========== ==========
```

2020-03-18 01:27 UTC, taalexander requested changes

2020-03-18 01:27 UTC, taalexander commented on test/benchmarks/pulse/schedule_construction.py
> +def sample_pulse(number_of_unique_pulses, number_of_channels):
Should this be closer to a verb + what it constructs? Something like `build_sample_pulse_schedule`?

2020-03-18 01:27 UTC, taalexander commented on test/benchmarks/pulse/schedule_construction.py
> +        self.empty_sched = sample_pulse(number_of_unique_pulses, 0)
Won't this amalgamate the timing of constructing all three schedules in each test?

2020-03-18 01:27 UTC, taalexander commented on test/benchmarks/pulse/schedule_construction.py
> +    def time_instruction_to_schedule(self, _, __):
Should this be included in a separate scheduling benchmark?

2020-03-18 14:51 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +        self.empty_sched = sample_pulse(number_of_unique_pulses, 0)
Right! Since `empty_sched` isn't used in this code, I'll get rid of it. Thanks

2020-03-18 15:37 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +def sample_pulse(number_of_unique_pulses, number_of_channels):
ok. I'll update it

2020-03-19 17:41 UTC, lcapelluto commented on test/benchmarks/pulse/schedule_construction.py
> +        if self.parametric_sched.stop_time >= self.sample_sched.start_time:
this is then equivalent to `if True:`?

2020-03-26 16:21 UTC, mtreinish reviewed
This is a good start, I've got a couple of questions inline. I also think we should add a benchmarks timing schedule assembly (just calling the build_schedule function). That way we have a baseline on how long it takes to construct pulse schedules as well as all the various modifiers to it.

2020-03-26 16:21 UTC, mtreinish commented on test/benchmarks/pulse/schedule_construction.py
> +    def time_instruction_to_schedule(self, _, __):
What is the intent of the measurement of this benchmark? Like are you trying to `time inst_map.add()` and `sched.union()`? Right now it's going to include the time of  all the object initialization and access to construct the necessary objects. If you think you want to include all of the time for those pieces then this is fine. But typically we're trying to be a bit more finer grained in what we benchmark.

2020-03-26 16:21 UTC, mtreinish commented on test/benchmarks/pulse/schedule_construction.py
> +        if self.parametric_sched.stop_time >= self.sample_sched.start_time:
Yeah, it feels like this will always be a necessary step I would remove the if here.

2020-03-26 16:21 UTC, mtreinish commented on test/benchmarks/pulse/schedule_construction.py
> +class ScheduleConstructionBench:
I feel like it would be good to include some benchmarks to build schedules from pulses. Something like: https://github.com/Qiskit/qiskit/blob/master/test/benchmarks/circuit_construction.py#L43-L44

2020-03-27 16:32 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +        if self.parametric_sched.stop_time >= self.sample_sched.start_time:
Okay, I'll remove it.

2020-03-27 16:32 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +    def time_instruction_to_schedule(self, _, __):
Yes, it was intended to measure the time taken to do the entire operation. But I now understand that this way of measurement not really ideal. I'll try to fix it.

2020-03-27 16:34 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +class ScheduleConstructionBench:
Okay, I'll include benchmarks to build sample and parameterized schedules.

2020-03-31 18:15 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +    def time_instruction_to_schedule(self, _, __):
Fixed in [4f68e59](https://github.com/Qiskit/qiskit/pull/848/commits/4f68e59810585735e43de503edc00b9a726b3e5f).

2020-04-01 18:07 UTC, mtreinish commented on test/benchmarks/pulse/schedule_construction.py
> +    my_pulse = SamplePulse(np.random.random(50),
Oh, I missed this in my first review, @lcapelluto is correct we should avoid any randomness in the benchmarks, even at setup. You can leverage random functions but only with a fixed seed. If the value here changes between each run it can cause jitter in the measured values over time. something like:

```suggestion
    rng = np.random.RandomState(42)
    pulse_array = rng.random(50)
    my_pulse = SamplePulse(pulse_array,
```

or just do a statically defined array

2020-04-01 18:07 UTC, mtreinish commented on test/benchmarks/pulse/schedule_construction.py
> +                             inst_map=self.add_inst_map))
I'm still a bit confused here; what are we measuring? Is it the time to run `union` or the time to run the scheduler on `self.qc` with the custom cmd def for the opaque gate? The 2 operations don't seem to be linked directly so it's not clear to me why both are being measured by this method.

2020-04-01 19:05 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +                             inst_map=self.add_inst_map))
It was intended to get the time taken to convert the instruction to a schedule and then take the union of all schedules. (as mentioned in issue - https://github.com/Qiskit/qiskit/issues/794)

2020-04-01 20:28 UTC, mtreinish commented on test/benchmarks/pulse/schedule_construction.py
> +                             inst_map=self.add_inst_map))
Ok sure I see it listed there, but it still doesn't make sense to me. Like are we interested in the performance of `union` or of `schedule` here? The two operations don't seem coupled to me, like we could easily statically define the output of `schedule` and do the union on that instead of invoking the scheduler. That benchmark would be more consistent and make it easier to identify changes in performance over time. Is there something coupling the 2 operations I'm missing? Normally you'd want to measure the time of the 2 operations separately that way when a regression (or an improvement) happens you know what is actually being effected by the change. If they're running together you don't know if it's the scheduler or union causing a regression just by looking at the numbers.

Looking at the other benchmarks here it's `Schedule.union()` we're interested in measuring for this class since everything else here is a synthetic benchmark measuring different constructors of schedules. The performance of these operations should be measured in isolation to ensure consistency. We should save timing for the scheduler to a separate class where we can better characterize it's performance

2020-04-01 20:56 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +                             inst_map=self.add_inst_map))
Okay. I'll fix it then.

2020-04-01 21:02 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +    my_pulse = SamplePulse(np.random.random(50),
Ok. I'll update it. Thank you!

2020-04-03 21:51 UTC, mtreinish reviewed
This looks a lot better, thanks for making the updates. Just one more inline comment, we should separate `time_instruction_to_schedule` into another class (maybe in another file). After that I think this is ready.

2020-04-03 21:51 UTC, mtreinish commented on test/benchmarks/pulse/schedule_construction.py
> +    def time_instruction_to_schedule(self, _, __):
Can we do this benchmark in a separate class? The rest of the benchmarks in this class are about bare schedule object construction and modification but this is running the scheduler and has different setup requirements. Normally I'd say it wasn't a big deal, but this has 2 implications in asv, first the grouping in high level view: https://qiskit.github.io/qiskit/ benchmarks are grouped by class. The second is that the setup runtime is impacted by this. `setup()`  gets run for each iteration of the benchmark including each parameter, so the cmd def creation in the setup gets run 54 times for each iteration of the benchmark class (which is typically 4 times, once for cache pre-warming and 3 times to get an error spread). Grouping benchmarks with similar or the same setup in the same class reduces this overhead so we don't balloon in runtime.

2020-04-03 21:57 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +    def time_instruction_to_schedule(self, _, __):
Ok. I'll move this to a separate class/file.

2020-04-06 19:51 UTC, mtreinish reviewed
A couple more inline comments and one question

2020-04-06 19:51 UTC, mtreinish commented on test/benchmarks/pulse/schedule_to_instruction_conversion.py
> +from qiskit.test.mock import FakeOpenPulse2Q
I don't think it'll be a huge problem in practice for this case, but it's something to think about if we start using this for more involved benchmarking. The fake backends in terra (even real fake ones like this, not just the ones which are snapshot of real devices) drift over time as we adjust the parameters in the fakes. If we change the pulse defaults in terra this could effect the results of the benchmarks unexpectedly because the fake changed, not because of a change in the `ScheduleToInstructionBench` or the functions being timed. It might be better to have a statically defined cmd def in this module or copy over the fake backend like: https://github.com/Qiskit/qiskit/tree/master/test/benchmarks/backends so we know a change in the backend doesn't change the timing.

2020-04-06 19:51 UTC, mtreinish commented on test/benchmarks/pulse/schedule_to_instruction_conversion.py
> +    def time_union_of_schedules(self, _, __):
Shouldn't this be in the schedule construction benchmark class instead of the schedule to instruction class?

2020-04-06 19:51 UTC, mtreinish commented on test/benchmarks/pulse/schedule_construction.py
> +        sched = self.sample_sched.shift(self.parametric_sched.stop_time)
Is the `shift()` call part of what is being measured here? Or is it just the `insert()` with the 2 params?

2020-04-06 21:31 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_construction.py
> +        sched = self.sample_sched.shift(self.parametric_sched.stop_time)
Yes, I think `shift` is part of what is being measured here.

@taalexander Any thoughts?

2020-04-06 21:33 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_to_instruction_conversion.py
> +    def time_union_of_schedules(self, _, __):
Yes, It should be in the schedule construction benchmark class. Thanks!

2020-04-06 21:36 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_to_instruction_conversion.py
> +    def time_union_of_schedules(self, _, __):
Fixed in [3adcbee](https://github.com/Qiskit/qiskit/pull/848/commits/3adcbee754793109b5c3e1d203af05d6b3e52786)

2020-04-06 21:41 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_to_instruction_conversion.py
> +from qiskit.test.mock import FakeOpenPulse2Q
Ok, I'll work on building the backends.

2020-04-06 22:01 UTC, taalexander commented on test/benchmarks/pulse/schedule_construction.py
> +        sched = self.sample_sched.shift(self.parametric_sched.stop_time)
`shift` is also being measured.

2020-04-07 13:12 UTC, SooluThomas commented on test/benchmarks/pulse/schedule_to_instruction_conversion.py
> +from qiskit.test.mock import FakeOpenPulse2Q
Fixed in [ff4d41a](https://github.com/Qiskit/qiskit/pull/848/commits/ff4d41a44722e918fca4fdff107d019720ef307d)

2020-04-08 17:31 UTC, mtreinish reviewed
This LGTM, thanks for keeping with this and updating everything based on my review comments. Before we merge it though I ran these new benchmarks locally and the benchmarks emit a ton of deprecation warnings (like so many that it filled up my terminals output buffer and I can't see the results)
```
/home/mtreinish/git/qiskit/qiskit/bench-test/lib/python3.8/site-packages/qiskit/pulse/pulse_lib/pulse.py:47: DeprecationWarning: Calling `Gaussian` with a channel is deprecated. Instantiate the new `Play` instruction directly with a pulse and a channel. In this case, please use: `Play(Gaussian(duration=25, amp=0.5j, sigma=4), DriveChannel(2047))`.
  warnings.warn("Calling `{}` with a channel is deprecated. Instantiate the new `Play` "
```


I understand the the pulse api is in flux and currently being refactored. But what is concerning me here is that the main value of asv is showing performance over time as we make changes. If/when we need to update the benchmark code to adapt to deprecation removals in the future that will invalidate the old results, not only in spirit (by changing the measurement) but the benchmarks are all actually implicitly versioned with the hash of the code. So changing the code treats the benchmark as a new version that can't be compared to the old one. The question I have is while we probably should update the api here to be the non-deprecated version so we can measure consistent results moving forward, is this new api going to stay around for longer than 3 months? Rebuilding the historical data set every time there is an api change won't scale (back-filling old data takes a very long time).

2020-04-08 20:22 UTC, taalexander commented
> I understand the the pulse api is in flux and currently being refactored. But what is concerning me here is that the main value of asv is showing performance over time as we make changes. If/when we need to update the benchmark code to adapt to deprecation removals in the future that will invalidate the old results, not only in spirit (by changing the measurement) but the benchmarks are all actually implicitly versioned with the hash of the code. So changing the code treats the benchmark as a new version that can't be compared to the old one. The question I have is while we probably should update the api here to be the non-deprecated version so we can measure consistent results moving forward, is this new api going to stay around for longer than 3 months? Rebuilding the historical data set every time there is an api change won't scale (back-filling old data takes a very long time)

The core content of the tests will remain relevant over time, I imagine this revision of the pulse API should stay current for > 3 months even as we move to the new builder interface which will sit on top of the IR these tests use.

2020-04-08 21:19 UTC, mtreinish commented
Ok, sounds good then let's update the API usage in the benchmarks here to avoid the deprecation warnings and then this is good to go from my perspective.

2020-04-09 19:02 UTC, SooluThomas commented
Lint error 
```
************* Module test.benchmarks.pulse.schedule_to_instruction_conversion
test/benchmarks/pulse/schedule_to_instruction_conversion.py:20:0: E0611: No name 'Play' in module 'qiskit.pulse' (no-name-in-module)
************* Module test.benchmarks.pulse.schedule_construction
test/benchmarks/pulse/schedule_construction.py:19:0: E0611: No name 'Play' in module 'qiskit.pulse' (no-name-in-module)
```

Will be fixed after Qiskit Terra release.

2020-04-10 13:41 UTC, mtreinish approved these changes
LGTM, thanks for keep with it

2020-04-10 14:05 UTC, merged