Bump Meta for Aqua 0.6.6
Qiskit/qiskit-metapackage pull request #886
Opened 2020-04-16 16:10 UTC by manoelmarques

### Summary

Bump the meta repo version to include:

qiskit-aqua==0.6.6

### Details and comments

2020-04-17 02:18 UTC, SooluThomas commented
The link to Aqua API references in TOC of [index.rst](https://github.com/Qiskit/qiskit-terra/blob/master/docs/apidocs/terra.rst) should be updated to `Qiskit Aqua <apidoc/aqua>`  as mentioned in #830

2020-04-20 14:49 UTC, mtreinish requested changes
Actually, looking at the state of aqua repo at 0.6.6 the change of index in https://github.com/Qiskit/qiskit/pull/886/commits/6d37de6e09eb368a9f85bedd92432c01d0b99985 is incorrect: https://github.com/Qiskit/qiskit-aqua/tree/0.6.6/docs/apidocs (~it's that way on master too~ it's actually correct on master, so we'll have do this for the 0.7 release). We should update it in aqua, but until that's done we can't change the index here. Otherwise it will result in the aqua docs not being in the TOC.

2020-04-20 15:01 UTC, manoelmarques commented
I removed the last incorrect commit.

2020-04-20 15:28 UTC, mtreinish approved these changes

2020-04-20 16:27 UTC, merged