Added valid Slack invite link
Qiskit/qiskit-metapackage pull request #978
Opened 2020-07-25 13:53 UTC by RafeyIqbalRahman

### Summary

I have added the valid Slack invite link and removed the invalid one.

### Details and comments

The valid link, i.e., https://qiskit.slack.com/join/shared_invite/zt-fybmq791-hYRopcSH6YetxycNPXgv~A#/, has been added in README.md. This PR target this open issue: https://github.com/Qiskit/qiskit/issues/976

2020-07-25 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=978) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=978) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=978) it.</sub>

2020-07-26 15:39 UTC, gunchamalik commented on README.md
> +We use [GitHub issues](https://github.com/Qiskit/qiskit/issues) for tracking requests and bugs. Please use our [slack](https://qiskit.slack.com/join/shared_invite/zt-fybmq791-hYRopcSH6YetxycNPXgv~A#/
change looks fine.

2020-07-26 15:52 UTC, gunchamalik commented
@RafeyIqbalRahman I was reviewing the changes and was about to approve when I realized that I am not seeing any issues with the link that is currently provided on the Readme.md. I have tried the links on the below links:

Element |  Readme.md
-- | --
qiskit-terra | https://github.com/Qiskit/qiskit-terra
qiskit-aer | https://github.com/Qiskit/qiskit-aer
qiskit-ignis | https://github.com/Qiskit/qiskit-ignis
qiskit-aqua | https://github.com/Qiskit/qiskit-aqua
Docs or Qiskit Meta-package | https://github.com/Qiskit/qiskit

So, I am wondering if this change is really required. Please let me know what error are you seeing when you click on those links.

2020-07-26 16:03 UTC, RafeyIqbalRahman commented
> @RafeyIqbalRahman I was reviewing the changes and was about to approve when I realized that I am not seeing any issues with the link that is currently provided on the Readme.md. I have tried the links on the below links:
> 
> Element	Readme.md
> qiskit-terra	https://github.com/Qiskit/qiskit-terra
> qiskit-aer	https://github.com/Qiskit/qiskit-aer
> qiskit-ignis	https://github.com/Qiskit/qiskit-ignis
> qiskit-aqua	https://github.com/Qiskit/qiskit-aqua
> Docs or Qiskit Meta-package	https://github.com/Qiskit/qiskit
> So, I am wondering if this change is really required. Please let me know what error are you seeing when you click on those links.

This is what I got when I opened the Slack link provided on Docs or Qiskit Meta-package	https://github.com/Qiskit/qiskit. Other repos have the same issue.

![issue](https://user-images.githubusercontent.com/59226057/88483732-43993180-cf83-11ea-8300-0def1fb7af1a.PNG)

2020-07-26 16:07 UTC, RafeyIqbalRahman commented
You won't face this issue in qiskit-terra https://github.com/Qiskit/qiskit-terra since my PR there has been merged.

![merge](https://user-images.githubusercontent.com/59226057/88483842-fff2f780-cf83-11ea-9f79-152fb147a5dc.PNG)

2020-07-26 16:42 UTC, gunchamalik commented
@RafeyIqbalRahman thx for confirming. I see the issue and the issue is resolved with this fix.

2020-07-26 16:42 UTC, gunchamalik approved these changes
fix resolves the issue.

2020-07-26 16:43 UTC, gunchamalik approved these changes
fix resolves the issue.

2020-07-26 16:44 UTC, gunchamalik approved these changes
fix resolves the issue

2020-07-26 17:07 UTC, RafeyIqbalRahman commented
You're welcome. :)

2020-08-05 07:52 UTC, gunchamalik submitted a review, later dismissed
attempting again to confirm my review.

2020-08-05 13:47 UTC, SooluThomas commented
The links (in qiskit.org) is working now. Please correct me if I'm wrong.

2020-08-05 14:16 UTC, RafeyIqbalRahman commented
Yes, @SooluThomas, the link on qiskit.org is valid. While in the README.md file, it's invalid.

2020-08-05 18:06 UTC, SooluThomas requested changes

2020-08-05 18:06 UTC, SooluThomas commented on README.md
> +We use [GitHub issues](https://github.com/Qiskit/qiskit/issues) for tracking requests and bugs. Please use our [slack](https://qiskit.slack.com/join/shared_invite/zt-fybmq791-hYRopcSH6YetxycNPXgv~A#/
I would suggest using this link - http://ibm.co/joinqiskitslack instead. 

```suggestion
We use [GitHub issues](https://github.com/Qiskit/qiskit/issues) for tracking requests and bugs. Please use our [slack](http://ibm.co/joinqiskitslack) for discussion and simple questions. For questions that are more suited for a forum we use the Qiskit tag in the [Stack Exchange](https://quantumcomputing.stackexchange.com/questions/tagged/qiskit).
```

2020-08-05 18:06 UTC, SooluThomas commented on CHANGELOG.md
> +- Added a visible image for API token access.
This need not be added.
```suggestion
```

2020-08-05 18:06 UTC, SooluThomas commented on docs/install.rst
> -.. image:: /images/figures/install_1.png
I don't think that the link to the image is broken? (https://qiskit.org/documentation/install.html#access-ibm-quantum-systems)

2020-08-05 18:06 UTC, SooluThomas commented on docs/install.rst
> +**2.**  Navigate to https://quantum-computing.ibm.com/account to view your account settings.
I would keep the image as it is and simply add a link to `My Account`
```suggestion
**2.**  Navigate to `My Account <https://quantum-computing.ibm.com/account>`__ to view your account settings.

.. image:: /images/figures/install_0.png
    :alt: Image of where to find the section 'My accounts'.
```

2020-08-05 18:36 UTC, RafeyIqbalRahman commented on CHANGELOG.md
> +- Added a visible image for API token access.
> This need not be added.

I'll remove this.

2020-08-05 18:36 UTC, RafeyIqbalRahman commented on README.md
> +We use [GitHub issues](https://github.com/Qiskit/qiskit/issues) for tracking requests and bugs. Please use our [slack](https://qiskit.slack.com/join/shared_invite/zt-fybmq791-hYRopcSH6YetxycNPXgv~A#/
> I would suggest using this link - http://ibm.co/joinqiskitslack instead.

Good suggestion.

2020-08-05 18:51 UTC, RafeyIqbalRahman commented on docs/install.rst
> -.. image:: /images/figures/install_1.png
> I don't think that the link to the image is broken? (https://qiskit.org/documentation/install.html#access-ibm-quantum-systems)

You're right. I don't know for whatever reason I was getting a 404 error. Nevermind.

2020-08-05 19:00 UTC, RafeyIqbalRahman commented on docs/install.rst
> -.. image:: /images/figures/install_1.png
> I don't think that the link to the image is broken? (https://qiskit.org/documentation/install.html#access-ibm-quantum-systems)

The link you've quoted is from the Documentation page. However, I'm referring to "broken" is this: 

![404](https://user-images.githubusercontent.com/59226057/89452893-d1410200-d777-11ea-8e21-8cee00a8a2fa.PNG)

2020-08-05 19:30 UTC, SooluThomas commented on docs/install.rst
> -.. image:: /images/figures/install_1.png
The docs are inside the `docs/` directory. You should be looking for the image inside `docs/` https://github.com/Qiskit/qiskit/blob/master/docs/images/figures/install_1.png

2020-08-05 19:31 UTC, SooluThomas commented on CHANGELOG.md
> -
I'm guessing that this was deleted by mistake?

2020-08-05 19:39 UTC, RafeyIqbalRahman commented on docs/install.rst
> -.. image:: /images/figures/install_1.png
Got it. Let me undo this.

2020-08-05 19:43 UTC, RafeyIqbalRahman commented on CHANGELOG.md
> -
But you said that there was no need of this.

2020-08-05 23:14 UTC, SooluThomas commented on CHANGELOG.md
> -
This was already in there. I asked you to just remove anything that you added to the CHANGELOG.md. Sorry for being unclear.

2020-08-06 04:19 UTC, RafeyIqbalRahman commented on CHANGELOG.md
> -
Got it. This has been added now.

2020-08-06 13:17 UTC, SooluThomas commented on CHANGELOG.md
>  - Increased the `qiskit-ibmq-provider` version to the latest release 0.3.3.
```suggestion

- Increased the `qiskit-ibmq-provider` version to the latest release 0.3.3.

```

2020-08-06 13:17 UTC, SooluThomas approved these changes
LGTM! Thanks!

2020-08-13 13:01 UTC, merged