Fix "Getting Started with Qiskit" dead links
Qiskit/qiskit-metapackage pull request #992
Opened 2020-08-04 20:53 UTC by filipecorrea

### Summary

Fixes https://github.com/Qiskit/qiskit.org/issues/647

Fix documentation and tutorials links on "Getting Started with Qiskit" page:
- Qiskit documentation -> https://qiskit.org/documentation
- Qiskit tutorials -> https://github.com/Qiskit/qiskit-tutorials/blob/master/start_here.ipynb

### Details and comments

N/A.

2020-08-04 20:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=992) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=992) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=992) it.</sub>

2020-08-04 21:37 UTC, filipecorrea commented
Travis build failure should not be related to this issue: `pyscf 1.7.4 has requirement scipy<1.5, but you have scipy 1.5.2.`

2020-08-05 18:16 UTC, SooluThomas requested changes

2020-08-05 18:16 UTC, SooluThomas commented on CHANGELOG.md
> +
This need not be added.
```suggestion
```

2020-08-05 18:16 UTC, SooluThomas commented on docs/getting_started.rst
> +- `Qiskit tutorials <https://github.com/Qiskit/qiskit-tutorials/blob/master/start_here.ipynb>`__
```suggestion
- `Qiskit tutorials <https://qiskit.org/documentation/tutorials/circuits/index.html>`__
```

2020-08-05 18:16 UTC, SooluThomas commented on docs/getting_started.rst
> +- `Qiskit documentation <https://qiskit.org/documentation>`__
I don't think this link has to be added here? @mtreinish

2020-08-05 18:22 UTC, filipecorrea commented on docs/getting_started.rst
> +- `Qiskit documentation <https://qiskit.org/documentation>`__
I agree with @SooluThomas. This link here seems redundant, but as it was broken, I decided to fix it. @mtreinish, please let me know if you agree with removing it.

2020-08-05 19:51 UTC, mtreinish submitted a review, later dismissed
Besides the inline comment we should not be using external html links for links to documentation. Instead we should use internal references: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role this way the links get generated correctly regardless of where the documentation is built or hosted.

2020-08-05 19:51 UTC, mtreinish commented on docs/getting_started.rst
> +- `Qiskit documentation <https://qiskit.org/documentation>`__
This does seem like a weird link to add, it's basically saying go back to the home page of the documentation which presumably is where you started to find this page. So I agree we should remove it. It'd be a different story if we had a front page for `apidoc` which is what I assume this was actually going for,

2020-08-05 20:10 UTC, filipecorrea commented
@mtreinish I got the internal link from [docs/index.rst](https://github.com/Qiskit/qiskit/blob/master/docs/index.rst). Can you please verify if that's the one you mentioned on https://github.com/Qiskit/qiskit/pull/992#pullrequestreview-461973819?

2020-08-05 23:17 UTC, SooluThomas approved these changes
LGTM! Thank you!

2020-08-13 10:40 UTC, mtreinish approved these changes

2020-08-13 10:41 UTC, merged